# Patch dependencies to run all tests against versions of the crate in the
# repository.
[patch.crates-io]
tower-async = { path = "tower-async" }
tower-async-layer = { path = "tower-async-layer" }
tower-async-service = { path = "tower-async-service" }
