name: create github release

on:
  push:
    tags:
      - tower-async-[0-9]+.*
      - tower-async-[a-z]+-[0-9]+.*

jobs:
  create-release:
    name: Create GitHub release
    # only publish from the origin repository
    if: github.repository_owner == 'plabayo'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/create-gh-release-action@v1.3.0
        with:
          prefix: "(tower-async)|(tower-async-[a-z]+)"
          changelog: "$prefix/CHANGELOG.md"
          title: "$prefix $version"
          branch: "(master)|(v[0-9]+.[0-9]+.x)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
